### ISSUE TITLE
Run the storymap locally (index.swig?)

### ISSUE THREAD

**Issue by hhkaos** [Esri/storymap-crowdsource#4]
Hi @ssylvia!

When [you say](https://github.com/Esri/storymap-crowdsource/blame/master/README.md#L43):

> 3. Edit index.html, find the configuration section on line 24 and paste in your application ID

Which index.html do you mean? I have found this [index.swig](https://github.com/Esri/storymap-crowdsource/blob/master/src/index.swig) but no index.html, and actually I'm not familiar with the "swig" format, is this a [JS template engine](https://github.com/paularmstrong/swig)?

Well, actually I have found some index.html but none is in a root directory, so I guess there are not the ones you mean, right?:

![idnexfiles2](https://cloud.githubusercontent.com/assets/826965/22814098/02223e06-ef51-11e6-83b8-6c3637d4fc3c.gif)

Thanks in advance,
Raul

**Comment by hhkaos** [comment]
I have found the answer myself... xD I realized that I needed to run ```$ npm install``` and ```$ grunt build``` first :).

One question, I realized that the app was always redirecting me to a secured version (HTTPs) and I had to setup a HTTPs certificate on my computer. Is it possible to run the app without HTTPs?

Thanks!

**Comment by ssylvia** [comment]
@hhkaos Sorry for the confusion the app is in Beta so the docs are not complete. The `index.swig` is just a JavaScript template engine we use that creates the `index.html` file. If you're adding the **appid** to the source files, edit the `index.swig` file. 

In general you should never edit any files under the `src/lib` folder. These files are all the open source libraries we use in the app. These never get commit to the repo and are downloaded/overwritten by bower. 

Unfortunately, it is not possible to run the app over http connection. Because the app includes login for the contributions, we require the app to use a secure connection. For your convenience, we've included a ssl certificate and development server with the repo. Running `grunt` will start the development server and allow you to access the files from the `src` folder. Or if you want to test the production version of the app, you can run `grunt test`. Because the certificate is not signed, you will be prompted with a browser security warning but you should not have to install a certificate on your computer; only on the final server.

**Comment by hhkaos** [comment]
Thanks @ssylvia ! I didn't see your answer before. Do you want me to do a quick contribution to the documentation to improve the installation process a little bit?

Cheers!

**Comment by ssylvia** [comment]
Sure, we always welcome contributions.

**Comment by hhkaos** [comment]
Done ;P
